version: '3.8'

services:
  app:
    build: .
    ports:
      - "8083:8083"

    environment:
      NODE_ENV: production
      PORT: 8083

      DB_HOST: host.docker.internal
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: upi_db

      REDIS_HOST: host.docker.internal
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""
      REDIS_DB: 0

      CORS_ORIGIN: "*"

    extra_hosts:
      - "host.docker.internal:host-gateway"

    restart: unless-stopped
